# Generated by Django 4.0.4 on 2022-05-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_date_joined_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('1', 'Admin'), ('2', 'Manager'), ('3', 'Employee')], default=7, null=True),
        ),
    ]
